use_frameworks!

platform :ios, '8.0'

target 'TPFCarousel_Example' do
  pod 'TPFCarousel', :path => '../'
  pod 'Reveal-SDK','20'

  target 'TPFCarousel_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
